### ISSUE TITLE
Failures with Mojolicious 6.49

### ISSUE THREAD

**Issue by eserte** [kberov/Mojolicious--Plugin--DSC#2]
Mojolicious 6.49 removed the throw method from Mojo::Exception. 6.50 reintroduced it again. Maybe you want to make sure your plugin is not build with 6.49 because it's causing test failures and is causing now red spots in the CPAN Testers Matrix: http://fast-matrix.cpantesters.org/?dist=Mojolicious-Plugin-DSC%201.005

**Comment by kberov** [comment]
Now it runs with 7.+.
It is very unlikely now anyone to go back to 6.49. 
Thanks.
