### ISSUE TITLE
Plugin "Charset" missing, maybe you need to install it?

### ISSUE THREAD

**Issue by andk** [kberov/Mojolicious--Plugin--DSC#3]
Plugin Charset has been removed from Mojolicious:

https://github.com/kraih/mojo/commit/503dec92a504a68165d62ad4cc22f5c05f5e6a9a#diff-58aa583130bcb90490b462f556b92f86

Sample fail report on plugin DSC:

http://www.cpantesters.org/cpan/report/99d9493c-4dfe-11e6-b0c2-948f8a86b6c9

HTH&&Thanks!

**Comment by kberov** [comment]
Yes, I noticed. I wIll have to update accordingly the code.
Thank you!

**Comment by kberov** [comment]
Fixed.
Thanks!
